# Generated by Django 5.1.2 on 2024-11-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_solar_output_solaroutput_otherattribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solaroutput',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='windoutput',
            name='created_at',
        ),
    ]
