# Generated by Django 5.1.2 on 2024-11-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_solaroutput_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('para_value', models.FloatField()),
            ],
        ),
    ]
