# Generated by Django 5.1.2 on 2024-11-08 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_projectassumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassumption',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.inputparameters'),
        ),
    ]
