# Generated by Django 5.1.2 on 2024-11-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_projectassumption_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassumption',
            name='group',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
