# Generated by Django 5.1.2 on 2024-11-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_projectassumption_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassumption',
            name='parameter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectassumption',
            name='unit',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
