# Generated by Django 5.1.2 on 2024-11-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_projectassumption_para_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
