# Generated by Django 5.1.2 on 2024-11-08 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_projectdetail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassumption',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.inputparameters'),
        ),
    ]
