# Generated by Django 5.1.2 on 2024-11-12 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_projectassumption_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solar_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_of_year', models.IntegerField()),
                ('day_of_month', models.IntegerField()),
                ('month', models.IntegerField()),
                ('time', models.IntegerField()),
                ('unit_solar1', models.FloatField()),
                ('unit_solar2', models.FloatField()),
                ('unit_solar3', models.FloatField()),
                ('unit_solar4', models.FloatField()),
                ('unit_solar5', models.FloatField()),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.inputparameters')),
            ],
        ),
        migrations.CreateModel(
            name='Wind_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_of_year', models.IntegerField()),
                ('day_of_month', models.IntegerField()),
                ('month', models.IntegerField()),
                ('time', models.IntegerField()),
                ('unit_wind1', models.FloatField()),
                ('unit_wind2', models.FloatField()),
                ('unit_wind3', models.FloatField()),
                ('unit_wind4', models.FloatField()),
                ('unit_wind5', models.FloatField()),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.inputparameters')),
            ],
        ),
    ]
