# Generated by Django 5.1.2 on 2024-11-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_wind_profile_unit_wind1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solar_profile',
            name='unit_solar1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solar_profile',
            name='unit_solar2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solar_profile',
            name='unit_solar3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solar_profile',
            name='unit_solar4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solar_profile',
            name='unit_solar5',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
