# Generated by Django 5.1.2 on 2024-11-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_solar_profile_unit_solar1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nh3_plant',
            name='capex_inr_mn',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
